### ISSUE TITLE
Antilag with high fps clients

### ISSUE THREAD

**Issue by wolf6542** [nobowned/rtcwPub#10]
It might be a silly question because I might be missing something, but why not get the client's fps from ps here, and divide 1000 by it?

https://github.com/nobowned/rtcwPub/blob/5e52441a15c97c8d29f7223b5dda3482648681a7/src/game/g_antilag.c#L74

**Comment by nobowned** [comment]
I never merged this code due to it not being tested. So I'm sure there are issues with it.

Since the PR and code mentioned is over two years old, I don't really remember tbh. Nor do I plan on revisiting it ATM.

The most I can offer is the pull request that is still open. There's a 2 year old comment I left that might help: https://github.com/nobowned/rtcwPub/pull/3
